//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParserTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolderFile
    {
        public int Id { get; set; }
        public Nullable<int> FolderPathId { get; set; }
        public Nullable<int> SqlFile { get; set; }
        public Nullable<int> SqlLine { get; set; }
        public Nullable<int> CsFile { get; set; }
        public Nullable<int> CsLine { get; set; }
        public Nullable<int> JsFile { get; set; }
        public Nullable<int> JsLine { get; set; }
        public Nullable<int> HtmlFile { get; set; }
        public Nullable<int> HtmlLine { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual FolderPath FolderPath { get; set; }
    }
}
