CREATE PROCEDURE AddMoney 
@IdFrom INT, 
@IdTo INT,
@Money SMALLINT
AS 
BEGIN
	BEGIN TRY
		BEGIN TRAN

			PRINT('TRYING TO SUBSTRACT MONEY FROM @IdFrom')
			UPDATE Client
			SET Money  = Money - @Money
			WHERE Id = @IdFrom

			PRINT('TRYING TO ADD MONEY TI @IdTo')
			UPDATE Client
			SET Money = Money + @Money
			WHERE Id = @IdTo

		COMMIT TRAN
	END TRY
	BEGIN CATCH 
		PRINT('TRANSACTION FAILED! ROLLING BACK DATABASE')
		ROLLBACK TRAN
		/*VISSZAÁLLÍTJA AZ ÖSSZES BEÁLLÍTÁST EREDETIRE*/
		PRINT('DATABASE ROLLED BACK')
	END CATCH

END